### ISSUE TITLE
IDBuffer fails to access memoryMap in enclosing Memory instance works if Memory is not retrieved from file

### ISSUE THREAD

**Issue by ikaruswill** [cs2103jan2015-w15-3j/main#100]

**Comment by ikaruswill** [comment]
Problem: Gson can not automatically deserialize the pure inner classes since their no-args constructor also need a reference to the containing Object which is not available at the time of deserialization. You can address this problem by either making the inner class static or by providing a custom InstanceCreator for it.

Implement InstanceCreator and registerTypeAdapter.

**Comment by jonathanlimsc** [comment]
Implemented
