### ISSUE TITLE
edit command allows conversion from floating task to deadline or event

### ISSUE THREAD

**Issue by paradite** [cs2103jan2015-w15-3j/main#102]
The user should be able to use edit command to convert a floating task into either a deadline, by supplying a end time, or into an event, by supply both start time and end time.

In case of wrong format supplied, a specific error should be shown to user.

**Comment by ikaruswill** [comment]
EditCommand already allows the conversion of a floating task to either a deadline or event, however specifying a start time without an end time to a floating task will not.

Will implement the specification of startTime as Type.DEADLINE.
