### ISSUE TITLE
EditCommand falsely detects a start time after end time error for editing floating tasks

### ISSUE THREAD

**Issue by jonathanlimsc** [cs2103jan2015-w15-3j/main#103]
Use case:

add run

Does not work:
edit <index> start 11pm 
edit<index> start 8pm
edit <index> start 11pm to 12 am <-- parsed as today's 12am

Works:
edit <index> start 10pm to 11pm
edit <index> end 8pm

**Comment by ikaruswill** [comment]
Closed. 12am recognised as a matter of semantics. User should specify 12am tomorrow for events that end at 12mn.
