### ISSUE TITLE
Implement the basic functions of SignalHandler class 

### ISSUE THREAD

**Issue by jonathanlimsc** [cs2103jan2015-w15-3j/main#31]

**Comment by ikaruswill** [comment]
MessagePrinter is now renamed to SignalHandler for intuitiveness.

**Comment by ikaruswill** [comment]
Append Todo in constructor. For all handler Signal types.

**Comment by ikaruswill** [comment]
Append Todo previousTodo, Todo newTodo in another constructor for EditHandler Signal types

**Comment by ikaruswill** [comment]
Accept Command type from dispatcher.

**Comment by ikaruswill** [comment]
SignalHandler now prints Signal messages
